// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoUHsiG8qISnMMVwAGO8w5DJpzNjWXJc4',
    appId: '1:296127284957:web:85eeb96df8a0b24b737d34',
    messagingSenderId: '296127284957',
    projectId: 'fir-cli-6b793',
    authDomain: 'fir-cli-6b793.firebaseapp.com',
    storageBucket: 'fir-cli-6b793.appspot.com',
    measurementId: 'G-VPSCM6FJRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQe-yVt55ZNN9gWUOsRZOhf8X7oC8lNaQ',
    appId: '1:296127284957:android:d8387888be293bfe737d34',
    messagingSenderId: '296127284957',
    projectId: 'fir-cli-6b793',
    storageBucket: 'fir-cli-6b793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjd2Et8hSih7tMkLqsMAtXZSJ2K4yiTo',
    appId: '1:296127284957:ios:1565646e23aa281a737d34',
    messagingSenderId: '296127284957',
    projectId: 'fir-cli-6b793',
    storageBucket: 'fir-cli-6b793.appspot.com',
    iosBundleId: 'com.firebase.firebaseCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkjd2Et8hSih7tMkLqsMAtXZSJ2K4yiTo',
    appId: '1:296127284957:ios:1565646e23aa281a737d34',
    messagingSenderId: '296127284957',
    projectId: 'fir-cli-6b793',
    storageBucket: 'fir-cli-6b793.appspot.com',
    iosBundleId: 'com.firebase.firebaseCli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoUHsiG8qISnMMVwAGO8w5DJpzNjWXJc4',
    appId: '1:296127284957:web:5c4bff1b00067619737d34',
    messagingSenderId: '296127284957',
    projectId: 'fir-cli-6b793',
    authDomain: 'fir-cli-6b793.firebaseapp.com',
    storageBucket: 'fir-cli-6b793.appspot.com',
    measurementId: 'G-H49F02EMJN',
  );
}
